### ISSUE TITLE
Opensubtitles: TypeError: Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by aamnah** [ItzBlitz98/torrentflix#35]
Getting this when trying to stream something..

```
/usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/node_modules/q/q.js:128
                    throw e;
                          ^
TypeError: Cannot read property 'params' of undefined
    at Object.exports.parseXmlLoginResult (/usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/lib/Utils.js:96:56)
    at /usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/lib/API.js:52:27
    at _fulfilled (/usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/node_modules/q/q.js:756:13)
    at /usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/node_modules/q/q.js:564:44
    at flush (/usr/local/lib/node_modules/torrentflix/node_modules/opensubtitles-client/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:355:11)
```

Config is:

```
"use_subtitle": "true",
"subtitle_language": "fre",
```

Version is 8.6.1

**Comment by ahivert** [comment]
can you please give the search engine used and the torrent chosen (name, size...) ?

**Comment by ItzBlitz98** [comment]
I think this is related to #36 let me have a look.

Edit: I don't think it is related i think maybe opensubtitles was just down temp ?

**Comment by aamnah** [comment]
> maybe opensubtitles was just down temp

most probably. it's gone now.
