### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by phr34k0** [ItzBlitz98/torrentflix#68]
Latest update broke everything. >_>

```
root@raspberrypi:~/torrentflix# torrentflix --version
9.0.0
root@raspberrypi:~/torrentflix# torrentflix
A new version of torrentflix is available run:

$ npm install -g torrentflix

Or go here to get it: https://github.com/ItzBlitz98/torrentflix
? What torrent site do you want to search? 1337x
? Search for a torrent:  arrow
Searching for arrow on 1337x...
No torrents found
? What torrent site do you want to search? Eztv
? Search for a torrent:  arrow
Searching for arrow on Eztv...
1) Arrow S05E02 HDTV x264-LOL [eztv] 276.17 MB  
? Torrent to stream (eg. 1, 2, 3..) or (b)ack or (e)xit:  1
Streaming Arrow S05E02 HDTV x264-LOL [eztv]

/usr/local/lib/node_modules/peerflix/node_modules/torrent-stream/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/simple-get/node_modules/unzip-response/index.js:2
const PassThrough = require('stream').PassThrough;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/peerflix/node_modules/torrent-stream/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/simple-get/index.js:8:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
root@raspberrypi:~/torrentflix# 

```

**Comment by evertonbob** [comment]
+1
same here

**Comment by ItzBlitz98** [comment]
This is a peerflix issue which has long since been fixed.
