### ISSUE TITLE
Crashes while using GetStrike

### ISSUE THREAD

**Issue by zeekhuge** [ItzBlitz98/torrentflix#74]
## Output
    ~$ torrentflix 
    A new version of torrentflix is available run:

    $ npm install -g torrentflix

    Or go here to get it: https://github.com/ItzBlitz98/torrentflix
    ? What torrent site do you want to search? GetStrike
    ? Search for a torrent:  archer
    Searching for archer on GetStrike...
    undefined:1

    <!DOCTYPE html>
    ^

    SyntaxError: Unexpected token <
        at Object.parse (native)
        at Request._callback (/usr/lib/node_modules/torrentflix/lib/strike.js:17:19)
        at Request.self.callback (/usr/lib/node_modules/torrentflix/node_modules/request/request.js:186:22)
        at emitTwo (events.js:87:13)
        at Request.emit (events.js:172:7)
        at Request.<anonymous> (/usr/lib/node_modules/torrentflix/node_modules/request/request.js:1081:10)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at IncomingMessage.<anonymous> (/usr/lib/node_modules/torrentflix/node_modules/request/request.js:1001:12)
        at IncomingMessage.g (events.js:260:16)

## torrentflix version
    ~$ torrentflix --version
    9.0.0

**Comment by ahivert** [comment]
Getstrike should be remove as it's down since some months now.

Le ven. 3 févr. 2017 09:31, Zubeen Tolani <notifications@github.com> a
écrit :

**Comment by ItzBlitz98** [comment]
1b5a7e30928a2ff789a9abc90fb52e508f18b192
